### ISSUE TITLE
Publisher missing

### ISSUE THREAD

**Issue by opoudjis** [relaton/relaton-etsi#3]
Retrieving "ETSI GS ZSM 012 V1.1.1", I notice that there is no publisher contributor. Could we please add ETSI as a publisher? It's an unnecessary inconsistency with other Relaton flavours.

ETSI, like OASIS, seems reluctant to use its full name, European Telecommunications Standards Institute, in its literature. In my opinion names should not be abbreviations, but I will defer to @ronaldtse on that question.

**Comment by ronaldtse** [comment]
> ETSI, like OASIS, seems reluctant to use its full name, European Telecommunications Standards Institute, in its literature. 

For ETSI, in particular, it is a French association headquartered in France, but the abbreviation comes from English...

Since ETSI is an official EU standards development organization, it also shouldn't display preference for any particular language...

I don't know how it works.

But I agree with @opoudjis that:
1. We should have "ETSI" (abbreviation) and "European Telecommunications Standards Institute" (full name) provided
2. "ETSI" should be specified as the preferred name.

**Comment by andrew2net** [comment]
The ETST dataset is updated https://github.com/relaton/relaton-data-etsi/blob/510a7e9e268400da1c2b353615abdccc10f851ec/data/ETSI_EG_200_053_V1_5_1_2004-06.yaml#L25
